<a href="https://colab.research.google.com/github/massidi/natural-language-NLP/blob/main/fouille_de_donnee_2_nltk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk

import pandas as pd

nltk.download('all')

In [ ]:
from nltk.stem import WordNetLemmatizer,PorterStemmer
from nltk.corpus import stopwords

In [ ]:
paragraph = """I have three visions for India. In 3000 years of our history, people from all over
               the world have come and invaded us, captured our lands, conquered our minds.
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours.
               Yet we have not done this to any other nation. We have not conquered anyone.
               We have not grabbed their land, their culture,
               their history and tried to enforce our way of life on them.
               Why? Because we respect the freedom of others.That is why my
               first vision is that of freedom. I believe that India got its first vision of
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India
               stands up to the world, no one will respect us. Only strength respects strength. We must be
               strong not only as a military power but also as an economic power. Both must go hand-in-hand.
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life.
               I see four milestones in my career"""

In [ ]:
sentences = nltk.sent_tokenize(paragraph)
print(sentences)
print(len(sentences))


['I have three visions for India.', 'In 3000 years of our history, people from all over\n               the world have come and invaded us, captured our lands, conquered our minds.', 'From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,\n               the French, the Dutch, all of them came and looted us, took over what was ours.', 'Yet we have not done this to any other nation.', 'We have not conquered anyone.', 'We have not grabbed their land, their culture,\n               their history and tried to enforce our way of life on them.', 'Why?', 'Because we respect the freedom of others.That is why my\n               first vision is that of freedom.', 'I believe that India got its first vision of\n               this in 1857, when we started the War of Independence.', 'It is this freedom that\n               we must protect and nurture and build on.', 'If we are not free, no one will respect us.', 'My second vision for India’s development.', 'For fift

In [ ]:
words = nltk.word_tokenize(paragraph)
print(words)
print(len(words))

['I', 'have', 'three', 'visions', 'for', 'India', '.', 'In', '3000', 'years', 'of', 'our', 'history', ',', 'people', 'from', 'all', 'over', 'the', 'world', 'have', 'come', 'and', 'invaded', 'us', ',', 'captured', 'our', 'lands', ',', 'conquered', 'our', 'minds', '.', 'From', 'Alexander', 'onwards', ',', 'the', 'Greeks', ',', 'the', 'Turks', ',', 'the', 'Moguls', ',', 'the', 'Portuguese', ',', 'the', 'British', ',', 'the', 'French', ',', 'the', 'Dutch', ',', 'all', 'of', 'them', 'came', 'and', 'looted', 'us', ',', 'took', 'over', 'what', 'was', 'ours', '.', 'Yet', 'we', 'have', 'not', 'done', 'this', 'to', 'any', 'other', 'nation', '.', 'We', 'have', 'not', 'conquered', 'anyone', '.', 'We', 'have', 'not', 'grabbed', 'their', 'land', ',', 'their', 'culture', ',', 'their', 'history', 'and', 'tried', 'to', 'enforce', 'our', 'way', 'of', 'life', 'on', 'them', '.', 'Why', '?', 'Because', 'we', 'respect', 'the', 'freedom', 'of', 'others.That', 'is', 'why', 'my', 'first', 'vision', 'is', 'that

In [ ]:
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [ ]:
import re
lemm= WordNetLemmatizer()
stemmer  = PorterStemmer()

corpus= []

for i in range(len(sentences)):
  words = re.sub('[^a-zA-Z]', ' ', sentences[i])

  words = words.lower()
  words = nltk.word_tokenize(sentences[i])


  # display(review)
  # print(words)
  words =[lemm.lemmatize(word) for word in words  if word not in set(stopwords.words('english')) ]

  words = ' '.join(words)
  corpus.append(sentences)

print("\n")

display(corpus)



[['I have three visions for India.',
  'In 3000 years of our history, people from all over\n               the world have come and invaded us, captured our lands, conquered our minds.',
  'From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,\n               the French, the Dutch, all of them came and looted us, took over what was ours.',
  'Yet we have not done this to any other nation.',
  'We have not conquered anyone.',
  'We have not grabbed their land, their culture,\n               their history and tried to enforce our way of life on them.',
  'Why?',
  'Because we respect the freedom of others.That is why my\n               first vision is that of freedom.',
  'I believe that India got its first vision of\n               this in 1857, when we started the War of Independence.',
  'It is this freedom that\n               we must protect and nurture and build on.',
  'If we are not free, no one will respect us.',
  'My second vision for India’s d

***Applying Lemmatization***

In [ ]:


corpus= []

for i in range(len(sentences)):
  review = re.sub('[^a-zA-Z]', ' ', sentences[i])
  review = review.lower()
  review = review.split()
  # display(review)
  # print(words)
  review =[lemm.lemmatize(word) for word in review  if word not in set(stopwords.words('english')) ]

  review = ' '.join(review)
  corpus.append(review)

print("\n")

# display(corpus)



In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features= 1500)
X = cv.fit_transform(corpus).toarray()

display(X)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

***Creating TF IDF model ***

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()

X = tf.fit_transform(corpus).toarray()

display(X)


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
messages = pd.read_csv("/content/drive/MyDrive/Cours fouille des données 2024/smsSpamCollection/SMSSpamCollection", sep="\t"
,names = ["label","message"])

In [ ]:
display(messages)

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:


corpus= []

for i in range(0, len(messages)):
  review = re.sub('[^a-zA-Z]', ' ', messages["message"][i])
  review = review.lower()
  review = review.split()
  # display(review)
  # print(words)
  review =[lemm.lemmatize(word) for word in review  if word not in set(stopwords.words('english')) ]

  review = ' '.join(review)
  corpus.append(review)
# display(corpus)

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(max_features=5000)

X = tf.fit_transform(corpus).toarray()

display(X)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

***Extract label and convert it into a numerical mean or let say binary Where 0 = spam and 1 = ham***

In [31]:
y= pd.get_dummies(messages["label"])
y=y.iloc[:,1].values

print(y)

from sklearn.model_selection import train_test_split


X_train,X_test, Y_train, Y_test = train_test_split(X ,y ,test_size= 0.2 ,random_state= 0)


[0 0 1 ... 0 0 0]


In [24]:
from sklearn.naive_bayes import MultinomialNB
spam_dec_model= MultinomialNB().fit(X_train, Y_train)
y_predic= spam_dec_model.predict(X_test)




***Apply confusion matrics***

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_m= confusion_matrix(Y_test,y_predic)

confusion_m


array([[944,  11],
       [  9, 151]])

***Check out the accuracy***

In [26]:
acc= accuracy_score(Y_test,y_predic)
acc

0.9820627802690582