<a href="https://colab.research.google.com/github/massidi/natural-language-NLP/blob/main/fouille_de_donnee_3_nltk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk

import pandas as pd

nltk.download('all')

In [ ]:
from nltk.stem import WordNetLemmatizer,PorterStemmer
from nltk.corpus import stopwords

In [ ]:
import re
lemm= WordNetLemmatizer()
stemmer  = PorterStemmer()

# corpus= []

# for i in range(len(sentences)):
#   words = re.sub('[^a-zA-Z]', ' ', sentences[i])

#   words = words.lower()
#   words = nltk.word_tokenize(sentences[i])


#   # display(review)
#   # print(words)
#   words =[lemm.lemmatize(word) for word in words  if word not in set(stopwords.words('english')) ]

#   words = ' '.join(words)
#   corpus.append(sentences)

# print("\n")

# display(corpus)



***Applying Lemmatization***

In [ ]:
messages = pd.read_csv("/content/drive/MyDrive/Cours fouille des données 2024/smsSpamCollection/SMSSpamCollection", sep="\t"
,names = ["label","message"])

In [ ]:
display(messages)

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:


corpus= []

for i in range(0, len(messages)):
  review = re.sub('[^a-zA-Z]', ' ', messages["message"][i])
  review = review.lower()
  review = review.split()
  # display(review)
  # print(words)
  review =[lemm.lemmatize(word) for word in review  if word not in set(stopwords.words('english')) ]

  review = ' '.join(review)
  corpus.append(review)
# display(corpus)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(max_features=5000)

X = tf.fit_transform(corpus).toarray()

display(X)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

***Extract label and convert it into a numerical mean or let say binary Where 0 = spam and 1 = ham***

In [ ]:
y= pd.get_dummies(messages["label"])
y=y.iloc[:,1].values

print(y)

from sklearn.model_selection import train_test_split


X_train,X_test, Y_train, Y_test = train_test_split(X ,y ,test_size= 0.2 ,random_state= 0)


[0 0 1 ... 0 0 0]


In [ ]:
from sklearn.naive_bayes import MultinomialNB
spam_dec_model= MultinomialNB().fit(X_train, Y_train)
y_predic= spam_dec_model.predict(X_test)




***Apply confusion matrics***

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_m= confusion_matrix(Y_test,y_predic)

confusion_m


array([[944,  11],
       [  9, 151]])

***Check out the accuracy***

In [ ]:
acc= accuracy_score(Y_test,y_predic)
acc

0.9820627802690582